config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "home/about" => "homes#about", as:"about"

  devise_for :users
  resources :users, only:[:index,:edit,:update,:show]

  resources :books, only:[:index,:edit,:update,:show,:create,:destroy] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create,:destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :book_id, uniqueness: { scope: :user_id }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length:{minimum:2, maximum:20}
  validates :introduction, length:{maximum:50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comment_params)
    book_comment.book_id = book.id
    book_comment.save
    redirect_back fallback_location: root_path
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back fallback_location: root_path
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.page(params[:page])
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page])
      render 'books/index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user!=current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.new(book_id: params[:book_id])
    favorite.save
    redirect_back fallback_location: root_path
  end

  def destroy
    favorite = current_user.favorites.find_by(book_id: params[:book_id])
    favorite.destroy
    redirect_back fallback_location: root_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    if @user!=current_user
      redirect_to user_path(current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-5 mx-auto'>
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <div class='form-group'>
          <%= f.label :title %>
          <%= f.text_field :title, class:'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :opinion %>
          <%= f.text_area :body, class:'form-control' %>
        </div>
        <%= f.submit 'Update Book', class:'btn btn-success mb-3' %>
      <% end %>

      <%= link_to 'Show', book_path(@book.id) %> |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/sidebar', user: current_user, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover'>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to (image_tag book.user.get_profile_image(50,50)), user_path(book.user.id) %></td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book.id), method: :delete, class:'text-danger' do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book.id), method: :post, class:'text-primary' do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </table>

      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/sidebar', user: @user, book: @new_book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td><%= image_tag @user.get_profile_image(50,50) %><br><%= link_to @user.name, user_path(@user.id) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book.id), method: :delete, class:'text-danger' do %>
                <i class="fas fa-heart"></i><%= @book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book.id), method: :post, class:'text-primary' do %>
                <i class="fas fa-heart"></i><%= @book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td>コメント数: <%= @book_comments.count %></td>
          <% if @user==current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book.id) %></td>
            <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
          <% end %>
        </tr>
      </table>

      <table>
        <% @book_comments.each do |book_comment| %>
          <tr>
            <td><%= image_tag book_comment.user.get_profile_image(50,50) %><br><%= link_to book_comment.user.name, user_path(book_comment.user.id) %></td>
            <td><%= book_comment.comment %></td>
            <% if book_comment.user==current_user %>
              <td><%= link_to 'Destroy', book_book_comment_path(@book.id, book_comment.id), method: :delete, class:'btn btn-danger btn-sm' %></td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </table>

      <%= form_with model: [@book,@book_comment], url: book_book_comments_path(@book.id) do |f| %>
        <div class='form-group'>
          <%= f.text_area :comment, class:'form-control' %>
        </div>
        <%= f.submit '送信' %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-5 mx-auto mt-3'>
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers </strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-6 mx-auto'>
      <h1 class='mt-3'>welcome to <i class="fas fa-book"></i><strong>Bookers </strong>!!</h1>
      <p class='mb-3'>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p class='mb-3'>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class='col-md-11 mx-auto'>
        <%= link_to 'Log in', new_user_session_path, class:'btn btn-info btn-block btn-sm' %><br>
        <%= link_to 'Sign up', new_user_registration_path, class:'btn btn-success btn-block btn-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-1 text-light" href='/'>Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i> logout
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> login
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class='mb-5'>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <footer>
      <div class='container'>
        <div class='row'>
          <p class='mx-auto'>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_flash.html.erb
<%= if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

app/views/users/_sidebar.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class='table'>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<%= link_to edit_user_path(user.id), class:'btn btn-outline-secondary btn-block' do %>
  <i class="fas fa-user-cog"></i>
<% end %><br>

<h2>New book</h2>
<% if book.errors.any? %>
  <%= book.errors.count %>件のエラーが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: book, url: books_path do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :opinion %>
    <%= f.text_area :body, class:'form-control' %>
  </div>
  <%= f.submit 'Create Book', class:'btn btn-success' %>
<% end %>

app/views/users/edit.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-5 mx-auto'>
      <h2>User Info</h2>

      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>


      <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
        <div class='form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, class:'form-control' %>
        </div>
        <%= f.label :image %><br>
        <%= f.file_field :profile_image, accept:'image/*', class:'mb-3' %>
        <div class='form-group'>
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class:'form-control' %>
        </div>
        <%= f.submit 'Update User', class:'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'users/sidebar', user: current_user, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <table class='table'>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(50,50) %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show',user_path(user.id) %></td>
          </tr>
        <% end %>
      </table>

      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container mt-3'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'sidebar', user: @user, book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover'>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to (image_tag @user.get_profile_image(50,50)), user_path(@user.id) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book.id), method: :delete, class:'text-danger' do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book.id), method: :post, class:'text-primary' do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %>
                <% end %>
              <% end %>
            </td>
            <td>コメント数: <%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>